defmodule ComponexMaterial.InputColors do
  @border [
    slate: "focus:border-slate-500 , after:border-slate-500 , peer-focus:after:border-slate-500 , peer-focus:before:border-slate-500" ,
    gray: "focus:border-gray-500 , after:border-gray-500 , peer-focus:after:border-gray-500 , peer-focus:before:border-gray-500" ,
    zinc: "focus:border-zinc-500 , after:border-zinc-500 , peer-focus:after:border-zinc-500 , peer-focus:before:border-zinc-500" ,
    neutral: "focus:border-neutral-500 , after:border-neutral-500 , peer-focus:after:border-neutral-500 , peer-focus:before:border-neutral-500" ,
    stone: "focus:border-stone-500 , after:border-stone-500 , peer-focus:after:border-stone-500 , peer-focus:before:border-stone-500" ,
    red: "focus:border-red-500 , after:border-red-500 , peer-focus:after:border-red-500 , peer-focus:before:border-red-500" ,
    orange: "focus:border-orange-500 , after:border-orange-500 , peer-focus:after:border-orange-500 , peer-focus:before:border-orange-500" ,
    amber: "focus:border-amber-500 , after:border-amber-500 , peer-focus:after:border-amber-500 , peer-focus:before:border-amber-500" ,
    yellow: "focus:border-yellow-500 , after:border-yellow-500 , peer-focus:after:border-yellow-500 , peer-focus:before:border-yellow-500" ,
    lime: "focus:border-lime-500 , after:border-lime-500 , peer-focus:after:border-lime-500 , peer-focus:before:border-lime-500" ,
    green: "focus:border-green-500 , after:border-green-500 , peer-focus:after:border-green-500 , peer-focus:before:border-green-500" ,
    emerald: "focus:border-emerald-500 , after:border-emerald-500 , peer-focus:after:border-emerald-500 , peer-focus:before:border-emerald-500" ,
    teal: "focus:border-teal-500 , after:border-teal-500 , peer-focus:after:border-teal-500 , peer-focus:before:border-teal-500" ,
    cyan: "focus:border-cyan-500 , after:border-cyan-500 , peer-focus:after:border-cyan-500 , peer-focus:before:border-cyan-500" ,
    sky: "focus:border-sky-500 , after:border-sky-500 , peer-focus:after:border-sky-500 , peer-focus:before:border-sky-500" ,
    blue: "focus:border-blue-500 , after:border-blue-500 , peer-focus:after:border-blue-500 , peer-focus:before:border-blue-500" ,
    indigo: "focus:border-indigo-500 , after:border-indigo-500 , peer-focus:after:border-indigo-500 , peer-focus:before:border-indigo-500" ,
    violet: "focus:border-violet-500 , after:border-violet-500 , peer-focus:after:border-violet-500 , peer-focus:before:border-violet-500" ,
    purple: "focus:border-purple-500 , after:border-purple-500 , peer-focus:after:border-purple-500 , peer-focus:before:border-purple-500" ,
    fuchsia: "focus:border-fuchsia-500 , after:border-fuchsia-500 , peer-focus:after:border-fuchsia-500 , peer-focus:before:border-fuchsia-500" ,
    pink: "focus:border-pink-500 , after:border-pink-500 , peer-focus:after:border-pink-500 , peer-focus:before:border-pink-500" ,
    rose: "focus:border-rose-500 , after:border-rose-500 , peer-focus:after:border-rose-500 , peer-focus:before:border-rose-500" ,
  ]

  @text [
    slate: "peer-focus:text-slate-500",
    gray: "peer-focus:text-gray-500",
    zinc: "peer-focus:text-zinc-500",
    neutral: "peer-focus:text-neutral-500",
    stone: "peer-focus:text-stone-500",
    red: "peer-focus:text-red-500",
    orange: "peer-focus:text-orange-500",
    amber: "peer-focus:text-amber-500",
    yellow: "peer-focus:text-yellow-500",
    lime: "peer-focus:text-lime-500",
    green: "peer-focus:text-green-500",
    emerald: "peer-focus:text-emerald-500",
    teal: "peer-focus:text-teal-500",
    cyan: "peer-focus:text-cyan-500",
    sky: "peer-focus:text-sky-500",
    blue: "peer-focus:text-blue-500",
    indigo: "peer-focus:text-indigo-500",
    violet: " peer-focus:text-violet-500",
    purple: "peer-focus:text-purple-500",
    fuchsia: "peer-focus:text-fuchsia-500",
    pink: "peer-focus:text-pink-500",
    rose: "peer-focus:text-rose-500"
  ]

  @base_color [
    amber: "border-amber-200 , text-amber-700 , text-amber-500 , text-amber-400 , placeholder-shown:border-amber-200 , placeholder-shown:border-t-amber-200 , disabled:bg-amber-50 , peer-placeholder-shown:text-amber-500 , peer-disabled:peer-placeholder-shown:text-amber-500 , before:border-amber-200 , after:border-amber-200" ,
    blue: "border-blue-200 , text-blue-700 , text-blue-500 , text-blue-400 , placeholder-shown:border-blue-200 , placeholder-shown:border-t-blue-200 , disabled:bg-blue-50 , peer-placeholder-shown:text-blue-500 , peer-disabled:peer-placeholder-shown:text-blue-500 , before:border-blue-200 , after:border-blue-200" ,
    cyan: "border-cyan-200 , text-cyan-700 , text-cyan-500 , text-cyan-400 , placeholder-shown:border-cyan-200 , placeholder-shown:border-t-cyan-200 , disabled:bg-cyan-50 , peer-placeholder-shown:text-cyan-500 , peer-disabled:peer-placeholder-shown:text-cyan-500 , before:border-cyan-200 , after:border-cyan-200" ,
    emerald: "border-emerald-200 , text-emerald-700 , text-emerald-500 , text-emerald-400 , placeholder-shown:border-emerald-200 , placeholder-shown:border-t-emerald-200 , disabled:bg-emerald-50 , peer-placeholder-shown:text-emerald-500 , peer-disabled:peer-placeholder-shown:text-emerald-500 , before:border-emerald-200 , after:border-emerald-200" ,
    fuchsia: "border-fuchsia-200 , text-fuchsia-700 , text-fuchsia-500 , text-fuchsia-400 , placeholder-shown:border-fuchsia-200 , placeholder-shown:border-t-fuchsia-200 , disabled:bg-fuchsia-50 , peer-placeholder-shown:text-fuchsia-500 , peer-disabled:peer-placeholder-shown:text-fuchsia-500 , before:border-fuchsia-200 , after:border-fuchsia-200" ,
    gray: "border-gray-200 , text-gray-700 , text-gray-500 , text-gray-400 , placeholder-shown:border-gray-200 , placeholder-shown:border-t-gray-200 , disabled:bg-gray-50 , peer-placeholder-shown:text-gray-500 , peer-disabled:peer-placeholder-shown:text-gray-500 , before:border-gray-200 , after:border-gray-200" ,
    green: "border-green-200 , text-green-700 , text-green-500 , text-green-400 , placeholder-shown:border-green-200 , placeholder-shown:border-t-green-200 , disabled:bg-green-50 , peer-placeholder-shown:text-green-500 , peer-disabled:peer-placeholder-shown:text-green-500 , before:border-green-200 , after:border-green-200" ,
    indigo: "border-indigo-200 , text-indigo-700 , text-indigo-500 , text-indigo-400 , placeholder-shown:border-indigo-200 , placeholder-shown:border-t-indigo-200 , disabled:bg-indigo-50 , peer-placeholder-shown:text-indigo-500 , peer-disabled:peer-placeholder-shown:text-indigo-500 , before:border-indigo-200 , after:border-indigo-200" ,
    lime: "border-lime-200 , text-lime-700 , text-lime-500 , text-lime-400 , placeholder-shown:border-lime-200 , placeholder-shown:border-t-lime-200 , disabled:bg-lime-50 , peer-placeholder-shown:text-lime-500 , peer-disabled:peer-placeholder-shown:text-lime-500 , before:border-lime-200 , after:border-lime-200" ,
    neutral: "border-neutral-200 , text-neutral-700 , text-neutral-500 , text-neutral-400 , placeholder-shown:border-neutral-200 , placeholder-shown:border-t-neutral-200 , disabled:bg-neutral-50 , peer-placeholder-shown:text-neutral-500 , peer-disabled:peer-placeholder-shown:text-neutral-500 , before:border-neutral-200 , after:border-neutral-200" ,
    orange: "border-orange-200 , text-orange-700 , text-orange-500 , text-orange-400 , placeholder-shown:border-orange-200 , placeholder-shown:border-t-orange-200 , disabled:bg-orange-50 , peer-placeholder-shown:text-orange-500 , peer-disabled:peer-placeholder-shown:text-orange-500 , before:border-orange-200 , after:border-orange-200" ,
    pink: "border-pink-200 , text-pink-700 , text-pink-500 , text-pink-400 , placeholder-shown:border-pink-200 , placeholder-shown:border-t-pink-200 , disabled:bg-pink-50 , peer-placeholder-shown:text-pink-500 , peer-disabled:peer-placeholder-shown:text-pink-500 , before:border-pink-200 , after:border-pink-200" ,
    purple: "border-purple-200 , text-purple-700 , text-purple-500 , text-purple-400 , placeholder-shown:border-purple-200 , placeholder-shown:border-t-purple-200 , disabled:bg-purple-50 , peer-placeholder-shown:text-purple-500 , peer-disabled:peer-placeholder-shown:text-purple-500 , before:border-purple-200 , after:border-purple-200" ,
    red: "border-red-200 , text-red-700 , text-red-500 , text-red-400 , placeholder-shown:border-red-200 , placeholder-shown:border-t-red-200 , disabled:bg-red-50 , peer-placeholder-shown:text-red-500 , peer-disabled:peer-placeholder-shown:text-red-500 , before:border-red-200 , after:border-red-200" ,
    rose: "border-rose-200 , text-rose-700 , text-rose-500 , text-rose-400 , placeholder-shown:border-rose-200 , placeholder-shown:border-t-rose-200 , disabled:bg-rose-50 , peer-placeholder-shown:text-rose-500 , peer-disabled:peer-placeholder-shown:text-rose-500 , before:border-rose-200 , after:border-rose-200" ,
    sky: "border-sky-200 , text-sky-700 , text-sky-500 , text-sky-400 , placeholder-shown:border-sky-200 , placeholder-shown:border-t-sky-200 , disabled:bg-sky-50 , peer-placeholder-shown:text-sky-500 , peer-disabled:peer-placeholder-shown:text-sky-500 , before:border-sky-200 , after:border-sky-200" ,
    slate: "border-slate-200 , text-slate-700 , text-slate-500 , text-slate-400 , placeholder-shown:border-slate-200 , placeholder-shown:border-t-slate-200 , disabled:bg-slate-50 , peer-placeholder-shown:text-slate-500 , peer-disabled:peer-placeholder-shown:text-slate-500 , before:border-slate-200 , after:border-slate-200" ,
    stone: "border-stone-200 , text-stone-700 , text-stone-500 , text-stone-400 , placeholder-shown:border-stone-200 , placeholder-shown:border-t-stone-200 , disabled:bg-stone-50 , peer-placeholder-shown:text-stone-500 , peer-disabled:peer-placeholder-shown:text-stone-500 , before:border-stone-200 , after:border-stone-200" ,
    teal: "border-teal-200 , text-teal-700 , text-teal-500 , text-teal-400 , placeholder-shown:border-teal-200 , placeholder-shown:border-t-teal-200 , disabled:bg-teal-50 , peer-placeholder-shown:text-teal-500 , peer-disabled:peer-placeholder-shown:text-teal-500 , before:border-teal-200 , after:border-teal-200" ,
    violet: "border-violet-200 , text-violet-700 , text-violet-500 , text-violet-400 , placeholder-shown:border-violet-200 , placeholder-shown:border-t-violet-200 , disabled:bg-violet-50 , peer-placeholder-shown:text-violet-500 , peer-disabled:peer-placeholder-shown:text-violet-500 , before:border-violet-200 , after:border-violet-200" ,
    yellow: "border-yellow-200 , text-yellow-700 , text-yellow-500 , text-yellow-400 , placeholder-shown:border-yellow-200 , placeholder-shown:border-t-yellow-200 , disabled:bg-yellow-50 , peer-placeholder-shown:text-yellow-500 , peer-disabled:peer-placeholder-shown:text-yellow-500 , before:border-yellow-200 , after:border-yellow-200" ,
    zinc: "border-zinc-200 , text-zinc-700 , text-zinc-500 , text-zinc-400 , placeholder-shown:border-zinc-200 , placeholder-shown:border-t-zinc-200 , disabled:bg-zinc-50 , peer-placeholder-shown:text-zinc-500 , peer-disabled:peer-placeholder-shown:text-zinc-500 , before:border-zinc-200 , after:border-zinc-200"
  ]
end
