defmodule ComponexMaterial.InputColors do
  @border [
    slate: "focus:border-slate-500, after:border-slate-500, peer-focus:after:border-slate-500, peer-focus:before:border-slate-500",
    gray: "focus:border-gray-500, after:border-gray-500, peer-focus:after:border-gray-500, peer-focus:before:border-gray-500",
    zinc: "focus:border-zinc-500, after:border-zinc-500, peer-focus:after:border-zinc-500, peer-focus:before:border-zinc-500",
    neutral: "focus:border-neutral-500, after:border-neutral-500, peer-focus:after:border-neutral-500, peer-focus:before:border-neutral-500",
    stone: "focus:border-stone-500, after:border-stone-500, peer-focus:after:border-stone-500, peer-focus:before:border-stone-500",
    red: "focus:border-red-500, after:border-red-500, peer-focus:after:border-red-500, peer-focus:before:border-red-500",
    orange: "focus:border-orange-500, after:border-orange-500, peer-focus:after:border-orange-500, peer-focus:before:border-orange-500",
    amber: "focus:border-amber-500, after:border-amber-500, peer-focus:after:border-amber-500, peer-focus:before:border-amber-500",
    yellow: "focus:border-yellow-500, after:border-yellow-500, peer-focus:after:border-yellow-500, peer-focus:before:border-yellow-500",
    lime: "focus:border-lime-500, after:border-lime-500, peer-focus:after:border-lime-500, peer-focus:before:border-lime-500",
    green: "focus:border-green-500, after:border-green-500, peer-focus:after:border-green-500, peer-focus:before:border-green-500",
    emerald: "focus:border-emerald-500, after:border-emerald-500, peer-focus:after:border-emerald-500, peer-focus:before:border-emerald-500",
    teal: "focus:border-teal-500, after:border-teal-500, peer-focus:after:border-teal-500, peer-focus:before:border-teal-500",
    cyan: "focus:border-cyan-500, after:border-cyan-500, peer-focus:after:border-cyan-500, peer-focus:before:border-cyan-500",
    sky: "focus:border-sky-500, after:border-sky-500, peer-focus:after:border-sky-500, peer-focus:before:border-sky-500",
    blue: "focus:border-blue-500, after:border-blue-500, peer-focus:after:border-blue-500, peer-focus:before:border-blue-500",
    indigo: "focus:border-indigo-500, after:border-indigo-500, peer-focus:after:border-indigo-500, peer-focus:before:border-indigo-500",
    violet: "focus:border-violet-500, after:border-violet-500, peer-focus:after:border-violet-500, peer-focus:before:border-violet-500",
    purple: "focus:border-purple-500, after:border-purple-500, peer-focus:after:border-purple-500, peer-focus:before:border-purple-500",
    fuchsia: "focus:border-fuchsia-500, after:border-fuchsia-500, peer-focus:after:border-fuchsia-500, peer-focus:before:border-fuchsia-500",
    pink: "focus:border-pink-500, after:border-pink-500, peer-focus:after:border-pink-500, peer-focus:before:border-pink-500",
    rose: "focus:border-rose-500, after:border-rose-500, peer-focus:after:border-rose-500, peer-focus:before:border-rose-500",
  ]

  @text [
    slate: "peer-focus:text-slate-500",
    gray: "peer-focus:text-gray-500",
    zinc: "peer-focus:text-zinc-500",
    neutral: "peer-focus:text-neutral-500",
    stone: "peer-focus:text-stone-500",
    red: "peer-focus:text-red-500",
    orange: "peer-focus:text-orange-500",
    amber: "peer-focus:text-amber-500",
    yellow: "peer-focus:text-yellow-500",
    lime: "peer-focus:text-lime-500",
    green: "peer-focus:text-green-500",
    emerald: "peer-focus:text-emerald-500",
    teal: "peer-focus:text-teal-500",
    cyan: "peer-focus:text-cyan-500",
    sky: "peer-focus:text-sky-500",
    blue: "peer-focus:text-blue-500",
    indigo: "peer-focus:text-indigo-500",
    violet: " peer-focus:text-violet-500",
    purple: "peer-focus:text-purple-500",
    fuchsia: "peer-focus:text-fuchsia-500",
    pink: "peer-focus:text-pink-500",
    rose: "peer-focus:text-rose-500"
  ]
end
